package ai.cc.chongming.auth.infrastructure;

import ai.cc.chongming.auth.domain.AuthErrorCode;
import ai.cc.chongming.auth.domain.AuthException;
import ai.cc.chongming.auth.domain.User;
import ai.cc.chongming.auth.domain.UserRepository;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Process-local user repository used when persistence is disabled, mirroring the review domain's
 * in-memory fallback so authentication keeps working without a database (for example in the test
 * profile). Identifiers are generated by an in-process sequence.
 *
 * @author wangli
 */
public class InMemoryUserRepository implements UserRepository {

    private final Map<String, User> usersByUsername = new ConcurrentHashMap<>();
    private final AtomicLong idSequence = new AtomicLong(0L);

    @Override
    public Optional<User> findByUsername(String username) {
        if (username == null) {
            return Optional.empty();
        }
        return Optional.ofNullable(usersByUsername.get(username));
    }

    @Override
    public Optional<User> findById(Long id) {
        if (id == null) {
            return Optional.empty();
        }
        return usersByUsername.values().stream()
                .filter(user -> id.equals(user.id()))
                .findFirst();
    }

    /** [AIREVIEW-PLAN-025] Company-internal uid lookup backing registration uniqueness checks. */
    @Override
    public Optional<User> findByCompanyUid(String companyUid) {
        if (companyUid == null || companyUid.isBlank()) {
            return Optional.empty();
        }
        String trimmed = companyUid.trim();
        return usersByUsername.values().stream()
                .filter(user -> trimmed.equals(user.companyUid()))
                .findFirst();
    }

    @Override
    public User save(User user) {
        User nonNullUser = Objects.requireNonNull(user, "user must not be null");
        User persisted = nonNullUser.id() == null ? nonNullUser.withId(idSequence.incrementAndGet()) : nonNullUser;
        if (persisted.companyUid() != null) {
            Optional<User> uidOwner = findByCompanyUid(persisted.companyUid());
            if (uidOwner.isPresent() && !uidOwner.orElseThrow().id().equals(persisted.id())) {
                throw new AuthException(AuthErrorCode.UID_TAKEN, "公司 UID 已被其他账号绑定");
            }
        }
        User existing = usersByUsername.putIfAbsent(persisted.username(), persisted);
        if (existing != null && !existing.id().equals(persisted.id())) {
            throw new AuthException(AuthErrorCode.USERNAME_TAKEN, "用户名已被占用");
        }
        return persisted;
    }

    @Override
    public List<UserView> findAll() {
        return usersByUsername.values().stream()
                .sorted(Comparator.comparing(User::username))
                .map(user -> new UserView(user.username(), user.displayName(), user.role(), user.companyUid()))
                .toList();
    }
}
