package ai.cc.chongming.auth.infrastructure;

import ai.cc.chongming.auth.domain.AuthErrorCode;
import ai.cc.chongming.auth.domain.AuthException;
import ai.cc.chongming.auth.domain.User;
import ai.cc.chongming.auth.domain.UserRepository;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Process-local user repository used when persistence is disabled, mirroring the review domain's
 * in-memory fallback so authentication keeps working without a database (for example in the test
 * profile). Identifiers are generated by an in-process sequence.
 *
 * @author wangli
 */
public class InMemoryUserRepository implements UserRepository {

    private final Map<String, User> usersByUsername = new ConcurrentHashMap<>();
    private final AtomicLong idSequence = new AtomicLong(0L);

    @Override
    public Optional<User> findByUsername(String username) {
        if (username == null) {
            return Optional.empty();
        }
        return Optional.ofNullable(usersByUsername.get(username));
    }

    @Override
    public Optional<User> findById(Long id) {
        if (id == null) {
            return Optional.empty();
        }
        return usersByUsername.values().stream()
                .filter(user -> id.equals(user.id()))
                .findFirst();
    }

    @Override
    public User save(User user) {
        User nonNullUser = Objects.requireNonNull(user, "user must not be null");
        User persisted = nonNullUser.id() == null ? nonNullUser.withId(idSequence.incrementAndGet()) : nonNullUser;
        User existing = usersByUsername.putIfAbsent(persisted.username(), persisted);
        if (existing != null && !existing.id().equals(persisted.id())) {
            throw new AuthException(AuthErrorCode.USERNAME_TAKEN, "用户名已被占用");
        }
        return persisted;
    }
}
