package ai.cc.chongming.review.application;

import ai.cc.chongming.review.domain.event.ReviewEventType;
import ai.cc.chongming.review.domain.exception.ReviewDomainException;
import ai.cc.chongming.review.domain.exception.ReviewErrorCode;
import ai.cc.chongming.review.domain.model.Claim;
import ai.cc.chongming.review.domain.model.DebateTopic;
import ai.cc.chongming.review.domain.model.Review;
import ai.cc.chongming.review.domain.model.ReviewDispatchCommand;
import ai.cc.chongming.review.domain.model.ReviewDispatchCommand.CommandId;
import ai.cc.chongming.review.domain.model.ReviewDispatchCommand.DispatchCommandStatus;
import ai.cc.chongming.review.domain.model.ReviewDispatchCommand.DispatchedAction;
import ai.cc.chongming.review.domain.repository.ReviewDebateStore;
import ai.cc.chongming.review.domain.repository.ReviewDispatchStore;
import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;
import java.util.stream.Collectors;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import static ai.cc.chongming.review.domain.model.ReviewTypes.*;

/**
 * [AIREVIEW-PLAN-024#方案3] Validates, persists and consumes directed dispatch commands. The
 * Director still decides which topics open, who challenges whom, whether a second round happens
 * and when to converge; this service freezes those decisions into verifiable envelopes and refuses
 * any attempt by a model to widen its own authority.
 *
 * <p>Validation before persistence: the recipient role is activated, the topic/claim/turn targets
 * belong to the current review, the allowed action applies to the current topic status, the round
 * matches the current debate stage, and the expiry lies in the future. Issuance is idempotent on
 * the command idempotencyKey; consumption, expiry and rejection are public runtime events.
 *
 * <p>The event publisher is resolved lazily: {@code ReviewEventService} collects every
 * {@code ReviewEventListener} (including the dispatcher that depends on this service), so a direct
 * constructor injection would form a cycle.
 *
 * @author wangli
 */
@Service
public class ReviewDispatchService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ReviewDispatchService.class);

    private final ReviewDispatchStore dispatchStore;
    private final ReviewDebateStore debateStore;
    private final ReviewEventPublisher eventPublisher;
    private final ObjectProvider<ReviewEventPublisher> publisherProvider;

    public ReviewDispatchService(ReviewDispatchStore dispatchStore, ReviewDebateStore debateStore) {
        this(dispatchStore, debateStore, ReviewEventPublisher.noop(), null);
    }

    public ReviewDispatchService(
            ReviewDispatchStore dispatchStore,
            ReviewDebateStore debateStore,
            ReviewEventPublisher eventPublisher) {
        this(dispatchStore, debateStore, eventPublisher, null);
    }

    @Autowired
    public ReviewDispatchService(
            ReviewDispatchStore dispatchStore,
            ReviewDebateStore debateStore,
            ObjectProvider<ReviewEventPublisher> publisherProvider) {
        this(dispatchStore, debateStore, null,
                Objects.requireNonNull(publisherProvider, "publisherProvider must not be null"));
    }

    private ReviewDispatchService(
            ReviewDispatchStore dispatchStore,
            ReviewDebateStore debateStore,
            ReviewEventPublisher eventPublisher,
            ObjectProvider<ReviewEventPublisher> publisherProvider) {
        this.dispatchStore = Objects.requireNonNull(dispatchStore, "dispatchStore must not be null");
        this.debateStore = Objects.requireNonNull(debateStore, "debateStore must not be null");
        this.eventPublisher = eventPublisher;
        this.publisherProvider = publisherProvider;
        if (eventPublisher == null && publisherProvider == null) {
            throw new IllegalArgumentException("either eventPublisher or publisherProvider is required");
        }
    }

    private ReviewEventPublisher publisher() {
        if (eventPublisher != null) {
            return eventPublisher;
        }
        ReviewEventPublisher resolved = publisherProvider.getIfAvailable();
        return resolved == null ? ReviewEventPublisher.noop() : resolved;
    }

    /**
     * Validates and persists one dispatch command proposed by the Director (or generated by the
     * server after a committed challenge). Replaying the same idempotencyKey returns the original
     * command without re-issuing it.
     */
    public DispatchIssueResult issue(Review review, DispatchProposal proposal) {
        Objects.requireNonNull(review, "review must not be null");
        Objects.requireNonNull(proposal, "proposal must not be null");
        ReviewDispatchCommand issued;
        boolean replayed;
        synchronized (review) {
            if (!review.id().equals(proposal.metadata().reviewId())) {
                throw new ReviewDomainException(ReviewErrorCode.REVIEW_ID_MISMATCH,
                        "dispatch command reviewId does not match aggregate");
            }
            ReviewDispatchCommand existing = dispatchStore
                    .findByIdempotencyKey(review.id(), proposal.metadata().idempotencyKey())
                    .orElse(null);
            if (existing != null) {
                return new DispatchIssueResult(existing, true);
            }
            ReviewDispatchCommand deduplicated = findPendingDuplicate(review, proposal);
            if (deduplicated != null) {
                // [AIREVIEW-PLAN-033#5] A re-dispatch restates live Director intent: refresh the
                // pending command's expiry so a still-wanted envelope does not silently time out
                // while queued. Once the Director stops re-dispatching, the command expires normally.
                ReviewDispatchCommand refreshed = deduplicated.withExpiresAt(proposal.expiresAt());
                dispatchStore.updateExpiry(refreshed);
                return new DispatchIssueResult(refreshed, true);
            }
            validateProposal(review, proposal);
            ReviewDispatchCommand command = new ReviewDispatchCommand(
                    new CommandId(UUID.randomUUID()),
                    review.id(),
                    review.attemptNo(),
                    review.stage(),
                    proposal.round(),
                    proposal.recipientRole(),
                    proposal.allowedAction(),
                    proposal.topicId(),
                    proposal.targetClaimId(),
                    proposal.targetTurnId(),
                    proposal.expiresAt(),
                    DispatchCommandStatus.PENDING,
                    proposal.metadata().idempotencyKey(),
                    Instant.now());
            dispatchStore.save(command);
            issued = command;
            replayed = false;
        }
        // Published outside the review lock: the dispatcher delivers the envelope on the listener
        // thread, and publishing here keeps issuance reentrant-safe.
        LOGGER.info("DISPATCH_COMMAND_ISSUED reviewId={} attemptNo={} commandId={} recipient={} action={} topicId={}",
                review.id().value(), review.attemptNo(), issued.commandId().value(),
                issued.recipientRole(), issued.allowedAction(),
                issued.topicId() == null ? "-" : issued.topicId().value());
        publisher().publish(ReviewEventDrafts.dispatchCommand(
                review, ReviewEventType.DISPATCH_COMMAND_ISSUED, issued,
                proposal.issuerRole(), proposal.issuedBy(), Map.of()));
        return new DispatchIssueResult(issued, replayed);
    }

    /**
     * Resolves the command referenced by a role's debate write invocation. The command must be
     * PENDING, unexpired, addressed to the invoking role, allow exactly the invoked action, and
     * still match the current stage and round. Errors are recoverable and name the role's legal
     * pending actions.
     */
    public ReviewDispatchCommand resolveForWrite(
            Review review, RoleType actorRole, CommandId commandId, DispatchedAction expectedAction) {
        Objects.requireNonNull(review, "review must not be null");
        Objects.requireNonNull(actorRole, "actorRole must not be null");
        Objects.requireNonNull(commandId, "commandId must not be null");
        Objects.requireNonNull(expectedAction, "expectedAction must not be null");
        synchronized (review) {
            ReviewDispatchCommand command = dispatchStore.findById(review.id(), commandId)
                    .filter(stored -> stored.attemptNo() == review.attemptNo())
                    .orElseThrow(() -> new ReviewDomainException(ReviewErrorCode.DISPATCH_COMMAND_REQUIRED,
                            "no dispatch command exists with commandId " + commandId.value()
                                    + "; legal pending actions: " + legalActions(review, actorRole)));
            if (command.status() == DispatchCommandStatus.PENDING && command.isExpiredAt(Instant.now())) {
                transition(review, command, DispatchCommandStatus.EXPIRED,
                        ReviewEventType.DISPATCH_COMMAND_EXPIRED, "EXPIRED_BEFORE_USE");
                throw new ReviewDomainException(ReviewErrorCode.DISPATCH_COMMAND_EXPIRED,
                        "dispatch command " + commandId.value() + " expired at " + command.expiresAt()
                                + "; legal pending actions: " + legalActions(review, actorRole));
            }
            if (command.status() != DispatchCommandStatus.PENDING) {
                throw new ReviewDomainException(ReviewErrorCode.DISPATCH_COMMAND_REQUIRED,
                        "dispatch command " + commandId.value() + " is already " + command.status()
                                + "; legal pending actions: " + legalActions(review, actorRole));
            }
            if (command.recipientRole() != actorRole) {
                throw new ReviewDomainException(ReviewErrorCode.DISPATCH_ACTOR_MISMATCH,
                        "dispatch command " + commandId.value() + " is addressed to "
                                + command.recipientRole() + ", not " + actorRole
                                + "; legal pending actions: " + legalActions(review, actorRole));
            }
            if (command.allowedAction() != expectedAction) {
                throw new ReviewDomainException(ReviewErrorCode.ILLEGAL_STATE_TRANSITION,
                        "dispatch command " + commandId.value() + " allows " + command.allowedAction()
                                + ", not " + expectedAction
                                + "; legal pending actions: " + legalActions(review, actorRole));
            }
            int stageRound = debateRoundOf(review.stage());
            if (stageRound != command.round()) {
                transition(review, command, DispatchCommandStatus.REJECTED,
                        ReviewEventType.DISPATCH_COMMAND_REJECTED, "STAGE_ROUND_DRIFT");
                throw new ReviewDomainException(ReviewErrorCode.ILLEGAL_STATE_TRANSITION,
                        "dispatch command round " + command.round()
                                + " no longer matches the current review stage " + review.stage()
                                + "; legal pending actions: " + legalActions(review, actorRole));
            }
            return command;
        }
    }

    /**
     * Marks the command consumed after the authorized write action committed successfully.
     */
    public void consume(Review review, ReviewDispatchCommand command) {
        Objects.requireNonNull(review, "review must not be null");
        Objects.requireNonNull(command, "command must not be null");
        synchronized (review) {
            ReviewDispatchCommand stored = dispatchStore.findById(review.id(), command.commandId())
                    .orElseThrow(() -> new IllegalStateException("dispatch command cannot be resolved for consumption"));
            if (stored.status() != DispatchCommandStatus.PENDING) {
                // Idempotent consumption: the write action itself already replayed.
                return;
            }
            transition(review, stored, DispatchCommandStatus.CONSUMED,
                    ReviewEventType.DISPATCH_COMMAND_CONSUMED, "WRITE_ACTION_COMMITTED");
        }
    }

    /**
     * Rejects every still-pending command of the attempt, for example when the review leaves the
     * debate stages or terminates. Already terminal commands are untouched.
     */
    public void rejectAllPending(Review review, String reason) {
        Objects.requireNonNull(review, "review must not be null");
        synchronized (review) {
            for (ReviewDispatchCommand pending : dispatchStore.findPending(review.id(), review.attemptNo())) {
                transition(review, pending, DispatchCommandStatus.REJECTED,
                        ReviewEventType.DISPATCH_COMMAND_REJECTED, reason);
            }
        }
    }

    /**
     * Exposes one persisted command for event-driven delivery.
     */
    public java.util.Optional<ReviewDispatchCommand> find(ReviewId reviewId, CommandId commandId) {
        return dispatchStore.findById(reviewId, commandId);
    }

    /**
     * Pending commands addressed to one role inside the attempt, deterministically ordered.
     */
    public List<ReviewDispatchCommand> pendingFor(ReviewId reviewId, int attemptNo, RoleType recipientRole) {
        return dispatchStore.findPendingByRecipient(reviewId, attemptNo, recipientRole);
    }

    /**
     * Public envelope text delivered to the recipient role; it names exactly the one authorized
     * write action and its targets, and nothing else.
     */
    public static String envelopeText(ReviewDispatchCommand command) {
        Objects.requireNonNull(command, "command must not be null");
        StringBuilder text = new StringBuilder("Directed dispatch envelope: commandId=")
                .append(command.commandId().value())
                .append("; allowedAction=").append(command.allowedAction())
                .append("; round=").append(command.round())
                .append("; topicId=").append(command.topicId() == null ? "-" : command.topicId().value());
        if (command.targetClaimId() != null) {
            text.append("; targetClaimId=").append(command.targetClaimId().value());
        }
        if (command.targetTurnId() != null) {
            text.append("; targetTurnId=").append(command.targetTurnId().value());
        }
        text.append("; expiresAt=").append(command.expiresAt()).append(". ");
        text.append("You may perform exactly this one write action by passing this commandId to the matching tool. ");
        text.append("Read tools may list public context, but no write action outside this envelope is authorized. ");
        text.append("First call list_persisted_debate_topics if you need the persisted topic facts.");
        if (command.allowedAction() == DispatchedAction.DEFENSE) {
            text.append(" 该命令授权你作为需求答辩人提交 SUPPORT 主张：调用 submit_claim 并传入此 commandId，"
                    + "subjectKey 必须与该议题一致，否则服务端拒绝。");
        }
        return text.toString();
    }

    private void validateProposal(Review review, DispatchProposal proposal) {
        int stageRound = debateRoundOf(review.stage());
        if (stageRound == 0) {
            throw new ReviewDomainException(ReviewErrorCode.ILLEGAL_STATE_TRANSITION,
                    "dispatch commands can be issued only during an active debate round, current stage is "
                            + review.stage());
        }
        if (proposal.round() != stageRound) {
            throw new ReviewDomainException(ReviewErrorCode.ILLEGAL_STATE_TRANSITION,
                    "dispatch round " + proposal.round() + " does not match the current review stage "
                            + review.stage());
        }
        boolean activeRecipient = review.roleActivations().stream()
                .anyMatch(activation -> activation.roleType() == proposal.recipientRole());
        if (!activeRecipient || proposal.recipientRole() == RoleType.DIRECTOR
                || proposal.recipientRole() == RoleType.JUDGE) {
            throw new ReviewDomainException(ReviewErrorCode.UNAUTHORIZED_ROLE,
                    "dispatch commands may only target an activated review role, not "
                            + proposal.recipientRole());
        }
        if (!proposal.expiresAt().isAfter(Instant.now())) {
            throw new IllegalArgumentException("dispatch command expiresAt must lie in the future");
        }
        Objects.requireNonNull(proposal.topicId(), "a dispatch command requires topicId");
        DebateTopic topic = debateStore.findTopic(review.id(), proposal.topicId())
                .orElseThrow(() -> new ReviewDomainException(ReviewErrorCode.REVIEW_ID_MISMATCH,
                        "dispatch topic does not belong to this review"));
        if (topic.status().isTerminal()) {
            throw new ReviewDomainException(ReviewErrorCode.ILLEGAL_STATE_TRANSITION,
                    "no dispatch command can target terminal topic " + topic.id().value()
                            + " (" + topic.status() + ")");
        }
        switch (proposal.allowedAction()) {
            case CHALLENGE -> {
                if (proposal.targetClaimId() == null) {
                    throw new ReviewDomainException(ReviewErrorCode.TARGET_CLAIM_REQUIRED,
                            "a challenge dispatch requires targetClaimId");
                }
                requireClaimInTopic(review.id(), topic, proposal.targetClaimId());
                if (topic.status() != DebateTopicStatus.OPEN && topic.status() != DebateTopicStatus.REBUTTED) {
                    throw new ReviewDomainException(ReviewErrorCode.ILLEGAL_STATE_TRANSITION,
                            "challenge is not applicable while topic " + topic.id().value() + " is "
                                    + topic.status() + "; applicable actions: "
                                    + applicableActions(topic));
                }
            }
            case REBUTTAL -> {
                if (proposal.targetTurnId() == null) {
                    throw new ReviewDomainException(ReviewErrorCode.TARGET_TURN_REQUIRED,
                            "a rebuttal dispatch requires targetTurnId");
                }
                debateStore.findTurn(review.id(), proposal.targetTurnId())
                        .filter(turn -> turn.topicId().equals(topic.id()))
                        .orElseThrow(() -> new ReviewDomainException(ReviewErrorCode.TARGET_TURN_REQUIRED,
                                "dispatch target turn does not belong to the dispatch topic"));
                if (topic.status() != DebateTopicStatus.CHALLENGED) {
                    throw new ReviewDomainException(ReviewErrorCode.ILLEGAL_STATE_TRANSITION,
                            "rebuttal is not applicable while topic " + topic.id().value() + " is "
                                    + topic.status() + "; applicable actions: "
                                    + applicableActions(topic));
                }
            }
            case POSITION_CHANGE -> {
                if (proposal.targetClaimId() == null) {
                    throw new ReviewDomainException(ReviewErrorCode.TARGET_CLAIM_REQUIRED,
                            "a position-change dispatch requires targetClaimId");
                }
                requireClaimInTopic(review.id(), topic, proposal.targetClaimId());
            }
            case EVIDENCE_REQUEST -> {
                if (proposal.targetClaimId() == null) {
                    throw new ReviewDomainException(ReviewErrorCode.TARGET_CLAIM_REQUIRED,
                            "an evidence-request dispatch requires targetClaimId");
                }
                requireClaimInTopic(review.id(), topic, proposal.targetClaimId());
            }
            case DEFENSE -> {
                // The requirement defender submits a SUPPORT claim on the topic's subjectKey; the
                // command targets the topic itself, never a claim or turn.
                if (proposal.targetClaimId() != null || proposal.targetTurnId() != null) {
                    throw new ReviewDomainException(ReviewErrorCode.TARGET_CLAIM_REQUIRED,
                            "a defense dispatch targets the topic only, not a claim or turn");
                }
                if (topic.status() != DebateTopicStatus.OPEN) {
                    throw new ReviewDomainException(ReviewErrorCode.ILLEGAL_STATE_TRANSITION,
                            "defense is not applicable while topic " + topic.id().value() + " is "
                                    + topic.status() + "; applicable actions: "
                                    + applicableActions(topic));
                }
            }
        }
    }

    /**
     * [内容级幂等] Returns an already-issued PENDING, unexpired command of this review attempt
     * whose (topicId, allowedAction, recipientRole, targetClaimId) four-tuple matches the
     * proposal, so the Director replaying the same dispatch intent never stacks duplicate
     * envelopes.
     */
    private ReviewDispatchCommand findPendingDuplicate(Review review, DispatchProposal proposal) {
        for (ReviewDispatchCommand pending : dispatchStore.findPending(review.id(), review.attemptNo())) {
            if (pending.isExpiredAt(Instant.now())) {
                continue;
            }
            if (Objects.equals(pending.topicId(), proposal.topicId())
                    && pending.allowedAction() == proposal.allowedAction()
                    && pending.recipientRole() == proposal.recipientRole()
                    && Objects.equals(pending.targetClaimId(), proposal.targetClaimId())) {
                LOGGER.info("DISPATCH_COMMAND_DEDUPED reviewId={} attemptNo={} commandId={} "
                                + "topicId={} allowedAction={} recipientRole={} targetClaimId={}",
                        review.id().value(), review.attemptNo(), pending.commandId().value(),
                        pending.topicId() == null ? "-" : pending.topicId().value(),
                        pending.allowedAction(), pending.recipientRole(),
                        pending.targetClaimId() == null ? "-" : pending.targetClaimId().value());
                return pending;
            }
        }
        return null;
    }

    private Claim requireClaimInTopic(ReviewId reviewId, DebateTopic topic, ClaimId claimId) {
        if (!topic.claimIds().contains(claimId)) {
            throw new ReviewDomainException(ReviewErrorCode.TARGET_CLAIM_REQUIRED,
                    "dispatch target claim is not part of the dispatch topic");
        }
        return debateStore.findClaim(reviewId, claimId)
                .orElseThrow(() -> new ReviewDomainException(ReviewErrorCode.TARGET_CLAIM_REQUIRED,
                        "dispatch target claim cannot be resolved"));
    }

    private void transition(
            Review review,
            ReviewDispatchCommand command,
            DispatchCommandStatus nextStatus,
            ReviewEventType eventType,
            String reason) {
        ReviewDispatchCommand updated = command.withStatus(nextStatus);
        dispatchStore.update(updated);
        LOGGER.info("DISPATCH_COMMAND_{} reviewId={} commandId={} recipient={} action={} reason={}",
                nextStatus.name(), review.id().value(), command.commandId().value(),
                command.recipientRole(), command.allowedAction(), reason);
        publisher().publish(ReviewEventDrafts.dispatchCommand(
                review, eventType, updated, null, reason, Map.of()));
    }

    private String legalActions(Review review, RoleType actorRole) {
        List<ReviewDispatchCommand> pending =
                dispatchStore.findPendingByRecipient(review.id(), review.attemptNo(), actorRole);
        if (pending.isEmpty()) {
            return "none (no pending dispatch command is addressed to " + actorRole + ")";
        }
        return pending.stream()
                .map(command -> command.allowedAction() + "(commandId=" + command.commandId().value()
                        + ", topicId=" + (command.topicId() == null ? "-" : command.topicId().value()) + ")")
                .collect(Collectors.joining(", "));
    }

    private static String applicableActions(DebateTopic topic) {
        return switch (topic.status()) {
            case OPEN -> "CHALLENGE, DEFENSE, POSITION_CHANGE, EVIDENCE_REQUEST";
            case CHALLENGED -> "REBUTTAL, POSITION_CHANGE, EVIDENCE_REQUEST";
            case REBUTTED -> "CHALLENGE, POSITION_CHANGE, EVIDENCE_REQUEST";
            default -> "none";
        };
    }

    private static int debateRoundOf(ReviewStage stage) {
        return switch (stage) {
            case DEBATE_ROUND_1 -> 1;
            case DEBATE_ROUND_2 -> 2;
            default -> 0;
        };
    }

    /**
     * Typed proposal boundary; the round is injected by the server from the current stage so the
     * model can never widen its own authority by naming another round.
     *
     * @author wangli
     */
    public record DispatchProposal(
            ReviewCommandMetadata metadata,
            RoleType recipientRole,
            DispatchedAction allowedAction,
            int round,
            TopicId topicId,
            ClaimId targetClaimId,
            TurnId targetTurnId,
            Instant expiresAt,
            RoleType issuerRole,
            String issuedBy) {

        public DispatchProposal {
            Objects.requireNonNull(metadata, "metadata must not be null");
            Objects.requireNonNull(recipientRole, "recipientRole must not be null");
            Objects.requireNonNull(allowedAction, "allowedAction must not be null");
            if (round < 1 || round > 2) {
                throw new IllegalArgumentException("round must be between 1 and 2");
            }
            Objects.requireNonNull(expiresAt, "expiresAt must not be null");
            issuerRole = issuerRole == null ? RoleType.DIRECTOR : issuerRole;
            issuedBy = issuedBy == null || issuedBy.isBlank() ? "DIRECTOR" : issuedBy;
        }
    }

    /**
     * Issue output with an explicit idempotent-replay indicator.
     *
     * @author wangli
     */
    public record DispatchIssueResult(ReviewDispatchCommand command, boolean replayed) {
    }
}
